[package]
cairo-version = "2.11.4"
name = "combat_game"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"
