services:
  dojo-by-example-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXAMPLE_DIR: "combat_game"
    container_name: dojobyexample
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    mem_limit: 4g
