name: Cairo-Dojo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOJO_VERSION: 1.6.1
  SCARB_VERSION: 2.10.1
  WORKING_DIRECTORY: ./backend/dojo_examples/combat_game

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Dojo release artifact
        run: |
          curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/v${{ env.DOJO_VERSION }}/dojo_v${{ env.DOJO_VERSION }}_linux_amd64.tar.gz
          tar -xzf dojo-linux-x86_64.tar.gz
          sudo mv sozo /usr/local/bin/

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Build contracts
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          sozo build

      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: sozo test

  check:
    runs-on: ubuntu-latest
    name: Check format
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Format
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: scarb fmt --check
        shell: bash
